// Generated by CoffeeScript 1.10.0
(function() {
  var Nume, Source;

  Source = require('../source');

  Nume = {
    firstName: function(gender) {
      var pool;
      if ((gender != null) && (gender !== 'male' && gender !== 'female')) {
        throw 'Invalid gender.';
      }
      if (gender == null) {
        pool = Source.firstName.male.concat(Source.firstName.female);
      } else {
        pool = Source.firstName[gender];
      }
      return pool[Math.floor(Math.random() * pool.length)];
    },
    lastName: function() {
      return Source.lastName[Math.floor(Math.random() * Source.lastName.length)];
    }
  };

  module.exports = Nume;

}).call(this);
