// Generated by CoffeeScript 1.10.0
(function() {
  var Nume, Source,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Source = require('../source');

  Nume = {
    firstName: function(gender) {
      var pool;
      if ((gender != null) && (gender !== 'male' && gender !== 'female')) {
        throw 'Invalid gender.';
      }
      if (gender == null) {
        pool = Source.firstName.male.concat(Source.firstName.female);
      } else {
        pool = Source.firstName[gender];
      }
      return pool[Math.floor(Math.random() * pool.length)];
    },
    lastName: function() {
      return Source.lastName[Math.floor(Math.random() * Source.lastName.length)];
    },
    isInDatabase: function(string) {
      var firstNameData, lastNameData, nameDatabase;
      firstNameData = Source.firstName.male.concat(Source.firstName.female);
      lastNameData = Source.lastName;
      nameDatabase = firstNameData.concat(lastNameData);
      return indexOf.call(nameDatabase, string) >= 0;
    },
    isRomanian: function(string) {
      var nameArray, romanianNames;
      nameArray = string.split(" ");
      romanianNames = nameArray.filter(function(name) {
        return Nume.isInDatabase(name);
      });
      return (romanianNames.length / nameArray.length * 100) >= 50;
    }
  };

  module.exports = Nume;

}).call(this);
